SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, 
DARBUOTOJAS.PROJEKTAS_ID, 
PROJEKTAS.PAVADINIMAS
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS.ID

SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAREIGOS,
DARBUOTOJAS.PROJEKTAS_ID, PROJEKTAS.PAVADINIMAS
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON PROJEKTAS.PAVADINIMAS = 'Galerija';

SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ,
PROJEKTAS.PAVADINIMAS
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS.ID 
AND PROJEKTAS.PAVADINIMAS = 'Projektų valdymas'

SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ,
PROJEKTAS.PAVADINIMAS
FROM DARBUOTOJAS 
JOIN PROJEKTAS
ON DARBUOTOJAS.ASMENS_KODAS LIKE '4%'
AND PROJEKTAS.PAVADINIMAS = 'Projektų valdymas'
AND DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS_ID

SELECT PAVADINIMAS, count(*) 
FROM DARBUOTOJAS
JOIN SKYRIUS
ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID
GROUP BY PAVADINIMAS
HAVING count() <= 5

SELECT PAVADINIMAS, count(*) 
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS.ID
GROUP BY PAVADINIMAS

SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, 
DARBUOTOJAS.PAREIGOS, SKYRIUS.PAVADINIMAS
FROM DARBUOTOJAS
JOIN SKYRIUS
ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID
AND DARBUOTOJAS.PAREIGOS != 'Vadovas'

INSERT INTO DARBUOTOJAS VALUES(
21, 'Pranas', 'Logis', '38807117896', NULL, date('2009-11-12'), NULL, NULL, NULL, NUll);

SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, 
SKYRIUS.PAVADINIMAS
FROM DARBUOTOJAS
LEFT JOIN SKYRIUS
ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID
WHERE DARBUOTOJAS.SKYRIUS_ID IS NULL;

SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, 
PAVADINIMAS, count(*)
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS.ID

SELECT PROJEKTAS.PAVADINIMAS, count(*) 
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID = PROJEKTAS.ID
GROUP BY PAVADINIMAS
HAVING count() > 4

SELECT DARBUOTOJAS.VARDAS, sum(DARBUOTOJAS.BAZINIS_ATLYGINIMAS + DARBUOTOJAS.PRIEDAI)
FROM DARBUOTOJAS
GROUP BY DARBUOTOJAS.VARDAS

SELECT sum(DARBUOTOJAS.BAZINIS_ATLYGINIMAS + DARBUOTOJAS.PRIEDAI), 
avg(DARBUOTOJAS.BAZINIS_ATLYGINIMAS + DARBUOTOJAS.PRIEDAI),
min(DARBUOTOJAS.BAZINIS_ATLYGINIMAS + DARBUOTOJAS.PRIEDAI),
max(DARBUOTOJAS.BAZINIS_ATLYGINIMAS + DARBUOTOJAS.PRIEDAI)
FROM DARBUOTOJAS


