SELECT * FROM DARBUOTOJAS WHERE ASMENS_KODAS = 38807200000;

SELECT DIRBA_NUO, ASMENS_KODAS FROM DARBUOTOJAS WHERE DIRBA_NUO BETWEEN date('2009-11-15') AND date('2012-12-12')	;

SELECT DIRBA_NUO, ASMENS_KODAS FROM DARBUOTOJAS WHERE DIRBA_NUO BETWEEN '2009-11-15' AND '2018-12-12';

SELECT VARDAS, SKYRIUS_ID,PROJEKTAS_ID FROM DARBUOTOJAS WHERE SKYRIUS_ID In (2, 3);

SELECT VARDAS, PAVARDĖ, ASMENS_KODAS FROM DARBUOTOJAS WHERE ASMENS_KODAS LIKE '4%' AND '6%';

SELECT * FROM DARBUOTOJAS WHERE ASMENS_KODAS LIKE '_____12%';

SELECT PROJEKTAS FROM DARBUOTOJAS WHERE PROJEKTAS LIKE 'a%';

SELECT PAREIGOS FROM DARBUOTOJAS WHERE PAREIGOS LIKE '%a%';

SELECT * FROM DARBUOTOJAS WHERE PAREIGOS IS NULL;

SELECT VARDAS, PAVARDĖ, DIRBA_NUO, PAREIGOS FROM DARBUOTOJAS WHERE DIRBA_NUO >= date('2011-02-12') AND PAREIGOS = "Programuotojas";

SELECT VARDAS, PAVARDĖ, SKYRIUS_ID, PROJEKTAS_ID FROM DARBUOTOJAS WHERE SKYRIUS_ID = 2 AND PROJEKTAS_ID =1;

SELECT * FROM DARBUOTOJAS WHERE VARDAS NOT LIKE 'A%';

SELECT VARDAS, PAVARDĖ, DIRBA_NUO FROM DARBUOTOJAS ORDER BY DIRBA_NUO;

SELECT VARDAS, PAVARDĖ, DIRBA_NUO FROM DARBUOTOJAS ORDER BY DIRBA_NUO DESC;

SELECT min(SKYRIUS_ID), max(SKYRIUS_ID) FROM DARBUOTOJAS;

SELECT PROJEKTAS_ID, count(*) FROM DARBUOTOJAS GROUP BY PROJEKTAS_ID ORDER BY count(*);




